### ISSUE TITLE
找不到上传和处理后的文件

### ISSUE THREAD

**Issue by miaowmint** [lixiaofei123/pdftoolbox#1]
请问我用docker部署以后添加了ssl并且用了nginx反代来代替ip:端口，使用起来是正常的，上传处理和下载没有问题，但是我在
/data/pdftoolbox/input
/data/pdftoolbox/output
这两个文件夹里并没有找到处理前的文件和处理后的文件，请问这是怎么回事

**Comment by lixiaofei123** [comment]
发一下命令看看

**Comment by miaowmint** [comment]
docker部署我用的是portainer，配置大概如下
![image](https://user-images.githubusercontent.com/58991169/136071333-31753303-0778-46f9-96a0-e780843048c9.png)
然后ssl和反代都是用的宝塔面板
![image](https://user-images.githubusercontent.com/58991169/136071566-7ab3b5d6-0c58-47a2-b662-9f8edbb896d1.png)
但是在/data/pdfcompress/output和/data/pdfcompress/input下没有文件，我也试过给777权限了
![image](https://user-images.githubusercontent.com/58991169/136071768-e176b16b-21a3-42fc-986f-2c917f75abf3.png)
![image](https://user-images.githubusercontent.com/58991169/136071798-9b534451-6447-4aec-9649-5bea5de4fea0.png)
网站打开和功能都是正常的，转换完可以下载，但是在后台就是找不到文件

**Comment by lixiaofei123** [comment]
没用过portainer，建议直接使用docker命令试试
